### ISSUE TITLE
Das eingebundene Logo wird nicht angezeigt

### ISSUE THREAD

**Issue by hakankoesekadam** [katgirl/isotope_documents#10]
Contao-Version 3.2.14 und die eingesetzte isotope_documents Version ist dev-master. Isotope an sich hat die Version 2.1.9. Das von dir eingebaute Logo von Isotope wird auch nicht in der generierten PDF-Datei angezeigt. Könntest du dir das mal angucken? Danke

**Comment by hakankoesekadam** [comment]
mit dem IMG-Tag scheint es irgendwie nicht zu funktionieren, aber mit einem Inserttag hat das geklappt --> https://community.contao.org/de/showthread.php?52487-Logo-in-PDF-Rechnung-einf%FCgen&p=342664&viewfull=1#post342664

**Comment by katgirl** [comment]
siehe #14
