### ISSUE TITLE
FR: Logo-Auswahl in Shop-Konfig

### ISSUE THREAD

**Issue by zonky2** [katgirl/isotope_documents#12]
mit den Templates kommt man fast ohne "anfassen" aus -lediglich für das Firmenlogo muss eine eigene Kopie erstellt werden...

... ggf. ist die Angabe/Auswahl eines Firmenlogos in der Shop-Konfig möglich - so wie "früher" ;-)

**Comment by xantippe** [comment]
zu spät gesehen: https://github.com/katgirl/isotope_documents/issues/4
