### ISSUE TITLE
Simple Tokens unter Contao nutzbar?

### ISSUE THREAD

**Issue by CodeAlDente** [katgirl/isotope_documents#16]
Ich bin mir nicht ganz sicher, aber kann ich die Werte von z.B. ##config_firstname## auch unter Contao nutzen? Simple Tokens gehen ja ohne weiteres nicht, aber etwas wie {{config::firstname}} auch nicht. Oder ist dies (bisher) nicht implementiert?

Das würde nämlich sehr viel Arbeit abnehmen weil man die Bestandsdaten dann nur noch einmal ändern müsste.

**Comment by katgirl** [comment]
Nein, da man im Template direkt drauf zugreifen kann:

```php
echo \Isotope::Config->company;
echo \Isotope::Config->firstname . ' ' \Isotope::Config->lastname;
```

**Comment by CodeAlDente** [comment]
Vielen Dank für deine Rückmeldung!

Da habe ich mich etwas unverständlich ausgedrückt. Ich würde die Daten, die in der Shop-Konfiguration vorliegen nämlich auch sehr gerne in Seiten bzw. in Artikeln nutzen. Beispielsweise für das Impressum, die Datenschutzerklärung und an anderen geeigneten Stellen.

Als Workaround greife ich aktuell auf die Erweiterung [terminal42/contao-inserttags](/terminal42/contao-inserttags) zurück, würde eine direkte Nutzung als Inserttags aber in jedem Fall vorziehen.

Lässt sich das umsetzen?

**Comment by katgirl** [comment]
ja, das ließe sich machen
