### ISSUE TITLE
documentNumber translation missing

### ISSUE THREAD

**Issue by fritzmg** [katgirl/isotope_documents#6]
The templates use `$GLOBALS['TL_LANG']['isoDocument']['documentNumber']`, however, there is no such translation anywhere in this extension or in Isotope itself (thus there is no output).

**Comment by katgirl** [comment]
see ff93ff3d57575421e17c7d941282121e98c757d1

**Comment by fritzmg** [comment]
Could you maybe make a new release that incorporates this change? Every now and then this issue pops up in the forum or IRC chat ;)
