### ISSUE TITLE
Product option listing in all iso_collection_XXX.html5 templates

### ISSUE THREAD

**Issue by wschwaiger** [katgirl/isotope_documents#8]
ORIGINAL

`<?php foreach($item['options'] as $option): ?>`
`><li><strong><?php echo $option['label']; ?>:</strong> <?php echo $option['value']; ?></li`
`<?php endforeach; ?>`

REPLACE

`<?php if(!empty($item['configuration'])): ?><?php foreach($item['configuration'] as $value): ?>`
`><li><strong><?php echo $value['label']; ?>:</strong> <?php echo (string) $value; ?></li`
`<?php endforeach; ?><?php endif; ?>``

The original code leads to funny numbers in the option values and is just not correct.

Many thanks for updating

**Comment by katgirl** [comment]
see ff93ff3
